apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod-cluster
  region: eu-west-1
  version: '1.17'

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 50
    labels: { role: workers }
    privateNetworking: true
    availabilityZones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]